# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classified_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created at')),
                ('classification', models.IntegerField(choices=[(0, 'Negative'), (1, 'Neutral'), (2, 'Positive')], verbose_name='Classification')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('tweet_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Tweet ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('screen_name', models.CharField(max_length=15, verbose_name="User's @")),
                ('text', models.CharField(max_length=140, verbose_name='Tweet')),
                ('valid', models.BooleanField(default=True, verbose_name='Valid')),
            ],
        ),
        migrations.AddField(
            model_name='classifiedtweet',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweend.Tweet', verbose_name='Tweet'),
        ),
        migrations.AddField(
            model_name='classifiedtweet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tweet'),
        ),
    ]
