# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedtweet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='screen_name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="User's @"),
        ),
    ]
