# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 17:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweend', '0002_auto_20170117_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayed_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created at')),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='displayed_count',
            field=models.IntegerField(default=0, verbose_name='Displayed Count'),
        ),
        migrations.AddField(
            model_name='tweetreport',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweend.Tweet', verbose_name='Tweet'),
        ),
        migrations.AddField(
            model_name='tweetreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
