# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweend', '0004_remove_tweet_displayed_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetreport',
            name='displayed_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Displayed at'),
        ),
    ]
